import { filesForHit } from "./mod-kind.ts";
import type { CatalogMod, SearchHit } from "./types.ts";
import { matchesModQuery, parseModQuery } from "./mod-query.ts";

/** Current Palworld dedicated / client line Palnest is built for. */
export const CURRENT_GAME = "1.0.5";
export const GAME_LINE = "1.0";
export const NEXT_GAME = "1.0.5";

/** 1.0 launch plus the patches that did not reshuffle DataTable rows. */
const V10 = ["1.0", "1.0.2", "1.0.4", "1.0.5"];
const V10_LATE = ["1.0.4", "1.0.5"];

export function parseGameVersion(raw: string): [number, number, number] {
  const cleaned = raw.trim().replace(/\+$/, "");
  const parts = cleaned.split(".").map((p) => Number.parseInt(p, 10));
  return [Number.isFinite(parts[0]) ? parts[0] : 0, Number.isFinite(parts[1]) ? parts[1] : 0, Number.isFinite(parts[2]) ? parts[2] : 0];
}

export function cmpGameVersion(a: string, b: string): number {
  const [am, ai, ap] = parseGameVersion(a);
  const [bm, bi, bp] = parseGameVersion(b);
  if (am !== bm) return am - bm;
  if (ai !== bi) return ai - bi;
  return ap - bp;
}

export function isPalworldOnePlus(v: string): boolean {
  return parseGameVersion(v)[0] >= 1;
}

/** A listed `1.0` covers every 1.0.x patch. `1.0+` covers 1.0 and later. Early Access 0.x never matches 1.0+. */
export function supportsGameVersion(listed: string[], current: string): boolean {
  if (!listed.length) return false;
  for (const l of listed) {
    if (l === current) return true;
    if (l.endsWith("+")) {
      if (cmpGameVersion(current, l.slice(0, -1)) >= 0) return true;
      continue;
    }
    const parts = l.split(".").filter(Boolean);
    const [lm, li] = parseGameVersion(l);
    const [cm, ci] = parseGameVersion(current);
    if (parts.length === 2 && lm === cm && li === ci) return true;
  }
  return false;
}

export const CATALOG: CatalogMod[] = [
  {
    id: "nx-palschema",
    name: "Pal Schema",
    author: "Okaetsu",
    version: "0.6.71",
    kind: "framework",
    source: "nexus",
    sourceId: "1018",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 842110,
    endorsements: 21440,
    category: "Frameworks",
    description:
      "JSON-driven Palworld 1.0 data framework. Pair with UE4SS 2281fa31. Required by most custom pal, item, and recipe packs.",
    gameVersions: [...V10],
    requires: ["ue4ss"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 1840,
    updatedAt: "2026-09-09T06:45:00.000Z",
    tags: ["framework", "required", "1.0"],
  },
  {
    id: "nx-palanalyzer",
    name: "Pal Analyzer",
    author: "Inhumanick",
    version: "2.4.1",
    kind: "ue4ss",
    source: "nexus",
    sourceId: "524",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 391200,
    endorsements: 9800,
    category: "UI",
    description: "Inspect pal stats, IVs, passives, Mutation, and Awakening from the party and palbox.",
    gameVersions: [...V10_LATE],
    requires: ["ue4ss"],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 220,
    updatedAt: "2026-09-12T00:00:00.000Z",
    tags: ["ui", "quality of life"],
  },
  {
    id: "nx-betterpalbox",
    name: "Better Palbox",
    author: "Okaetsu",
    version: "1.8.0",
    kind: "palschema",
    source: "nexus",
    sourceId: "1402",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 512440,
    endorsements: 13200,
    category: "Quality of Life",
    description: "Sort, search, and filter the palbox, including Global Palbox transfers. Server-safe PalSchema pack.",
    gameVersions: [...V10],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 96,
    updatedAt: "2026-09-02T00:00:00.000Z",
    tags: ["qol", "palbox"],
  },
  {
    id: "nx-mapunlock",
    name: "Map Revealer",
    author: "LazyAeon",
    version: "1.4.0",
    kind: "pak",
    source: "nexus",
    sourceId: "88",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 1103400,
    endorsements: 24100,
    category: "Map",
    description: "Unfog Palpagos, the World Tree, and Sky Islands. Client-side PAK, not needed on dedicated.",
    gameVersions: [...V10],
    requires: [],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 4100,
    updatedAt: "2026-08-19T00:00:00.000Z",
    tags: ["map", "client", "1.0"],
  },
  {
    id: "nx-stack",
    name: "Configurable Stack Sizes",
    author: "PalTech",
    version: "3.1.0",
    kind: "palschema",
    source: "nexus",
    sourceId: "211",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 678900,
    endorsements: 15440,
    category: "Gameplay",
    description: "Raises item stack caps via PalSchema tables. Safe to mirror to the dedicated server.",
    gameVersions: [...V10],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 48,
    updatedAt: "2026-09-04T00:00:00.000Z",
    tags: ["economy", "server"],
  },
  {
    id: "nx-breed",
    name: "Breeding Preview",
    author: "EggLab",
    version: "1.0.2",
    kind: "ue4ss",
    source: "nexus",
    sourceId: "1774",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 221000,
    endorsements: 6100,
    category: "Breeding",
    description: "Shows likely offspring passives and Mutation odds before you commit a pair.",
    gameVersions: [...V10_LATE],
    requires: ["ue4ss"],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 180,
    updatedAt: "2026-09-08T00:00:00.000Z",
    tags: ["breeding", "1.0"],
  },
  {
    id: "nx-basecap",
    name: "Base Camp Limits",
    author: "Denworks",
    version: "2.0.4",
    kind: "palschema",
    source: "nexus",
    sourceId: "903",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 404120,
    endorsements: 8900,
    category: "Base",
    description: "Raises base camp worker and building caps. Must be installed on the 1.0 dedicated server.",
    gameVersions: [...V10],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 32,
    updatedAt: "2026-09-11T00:00:00.000Z",
    tags: ["base", "server"],
  },
  {
    id: "nx-nodurability",
    name: "Durable Tools",
    author: "Forgeleaf",
    version: "1.5.0",
    kind: "palschema",
    source: "nexus",
    sourceId: "340",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 290440,
    endorsements: 5400,
    category: "Gameplay",
    description: "Slows weapon and tool decay. PalSchema values, server authoritative. Last built for Early Access 0.7.",
    gameVersions: ["0.6.8", "0.7.1"],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 18,
    updatedAt: "2026-06-02T00:00:00.000Z",
    tags: ["balance", "legacy"],
  },
  {
    id: "st-restskin",
    name: "Restful HUD",
    author: "workshop_dusk",
    version: "1.3.0",
    kind: "pak",
    source: "steam",
    sourceId: "3488211901",
    url: "https://steamcommunity.com/app/1623730/workshop/",
    downloads: 88200,
    endorsements: 2100,
    category: "UI",
    description: "Quieter HUD chrome and readable World Tree markers. Workshop PAK.",
    gameVersions: [...V10],
    requires: [],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 12600,
    updatedAt: "2026-09-01T00:00:00.000Z",
    tags: ["hud", "workshop"],
  },
  {
    id: "st-admin",
    name: "Den Admin Commands",
    author: "hollowisle",
    version: "1.0.0",
    kind: "ue4ss",
    source: "steam",
    sourceId: "3490012210",
    url: "https://steamcommunity.com/app/1623730/workshop/",
    downloads: 44120,
    endorsements: 980,
    category: "Server",
    description: "In-game admin slash commands for dedicated 1.0 servers. UE4SS Lua.",
    gameVersions: [...V10],
    requires: ["ue4ss"],
    serverCompatible: true,
    clientCompatible: false,
    sizeKb: 64,
    updatedAt: "2026-09-08T00:00:00.000Z",
    tags: ["admin", "server"],
  },
  {
    id: "st-extrafasttravel",
    name: "Trail Markers",
    author: "cartograph",
    version: "1.1.0",
    kind: "pak",
    source: "steam",
    sourceId: "3471109988",
    url: "https://steamcommunity.com/app/1623730/workshop/",
    downloads: 120440,
    endorsements: 3300,
    category: "Map",
    description: "Place custom fast-travel flags on Palpagos and the Sky Islands.",
    gameVersions: ["1.0", "1.0.2"],
    requires: [],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 8900,
    updatedAt: "2026-08-16T00:00:00.000Z",
    tags: ["travel"],
  },
  {
    id: "cf-terraria-pals",
    name: "Tidebound Pals",
    author: "Shoalcraft",
    version: "0.3.8",
    kind: "palschema",
    source: "curseforge",
    sourceId: "1102944",
    url: "https://www.curseforge.com/",
    downloads: 67300,
    endorsements: 1400,
    category: "Pals",
    description: "Adds a small set of water-type pals through PalSchema. Early Access pack — will not boot on 1.0.",
    gameVersions: ["0.6.8"],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 15400,
    updatedAt: "2026-05-22T00:00:00.000Z",
    tags: ["pals", "legacy"],
  },
  {
    id: "cf-recipebook",
    name: "Expanded Workbench",
    author: "Kiln & Co",
    version: "2.2.1",
    kind: "palschema",
    source: "curseforge",
    sourceId: "1087712",
    url: "https://www.curseforge.com/",
    downloads: 154800,
    endorsements: 4100,
    category: "Crafting",
    description: "Additional furniture and production recipes, including Soralite benches. PalSchema, server + client.",
    gameVersions: [...V10],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 420,
    updatedAt: "2026-09-06T00:00:00.000Z",
    tags: ["crafting"],
  },
  {
    id: "cf-performancepak",
    name: "Lean World LODs",
    author: "Framerate Guild",
    version: "2.0.0",
    kind: "pak",
    source: "curseforge",
    sourceId: "1093301",
    url: "https://www.curseforge.com/",
    downloads: 98000,
    endorsements: 2600,
    category: "Performance",
    description: "Aggressive foliage LODs for the doubled 1.0 map. Helps 32-slot worlds. Optional on clients.",
    gameVersions: [...V10],
    requires: [],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 26800,
    updatedAt: "2026-08-30T00:00:00.000Z",
    tags: ["performance", "1.0"],
  },
  {
    id: "nx-deathchest",
    name: "Grave Cache",
    author: "QuietCart",
    version: "1.5.0",
    kind: "ue4ss",
    source: "nexus",
    sourceId: "612",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 188200,
    endorsements: 4700,
    category: "Gameplay",
    description: "Drops a recoverable cache on death instead of scattering items. Server Lua.",
    gameVersions: [...V10_LATE],
    requires: ["ue4ss"],
    serverCompatible: true,
    clientCompatible: false,
    sizeKb: 40,
    updatedAt: "2026-09-14T00:00:00.000Z",
    tags: ["death", "server"],
  },
  {
    id: "nx-hdicons",
    name: "Crisp Item Icons",
    author: "Atelier North",
    version: "0.8.0",
    kind: "pak",
    source: "nexus",
    sourceId: "1555",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 76000,
    endorsements: 1900,
    category: "Visuals",
    description: "Replaces inventory icons. Last Early Access PAK — 1.0 added new item art.",
    gameVersions: ["0.6.5", "0.6.8", "0.7.1", "0.7.2"],
    requires: [],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 48100,
    updatedAt: "2026-07-01T00:00:00.000Z",
    tags: ["visuals", "legacy"],
  },
  {
    id: "nx-brokenlegacy",
    name: "Old World Minimap",
    author: "Cartograph Classic",
    version: "0.2.0",
    kind: "ue4ss",
    source: "nexus",
    sourceId: "77",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 41000,
    endorsements: 400,
    category: "Map",
    description: "Pre-Feybreak minimap hook. Missing Scripts/main.lua after Palworld 1.0.",
    gameVersions: ["0.4.15", "0.5.2"],
    requires: ["ue4ss"],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 90,
    updatedAt: "2025-04-11T00:00:00.000Z",
    tags: ["legacy", "broken"],
  },
  {
    id: "st-weather",
    name: "Soft Storms",
    author: "climate_kit",
    version: "1.1.0",
    kind: "pak",
    source: "steam",
    sourceId: "3466001122",
    url: "https://steamcommunity.com/app/1623730/workshop/",
    downloads: 33000,
    endorsements: 720,
    category: "Visuals",
    description: "Tones down storm particle density on the larger 1.0 map. Client visual PAK.",
    gameVersions: [...V10],
    requires: [],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 7600,
    updatedAt: "2026-08-21T00:00:00.000Z",
    tags: ["weather"],
  },
  {
    id: "nx-rescue",
    name: "Recall Party",
    author: "Whistlework",
    version: "1.6.2",
    kind: "ue4ss",
    source: "nexus",
    sourceId: "1288",
    url: "https://www.nexusmods.com/palworld/mods",
    downloads: 143000,
    endorsements: 3600,
    category: "Quality of Life",
    description: "Keybind to recall all pals, even when stuck in Sky Island geometry. Client UE4SS.",
    gameVersions: [...V10],
    requires: ["ue4ss"],
    serverCompatible: false,
    clientCompatible: true,
    sizeKb: 28,
    updatedAt: "2026-09-03T00:00:00.000Z",
    tags: ["qol"],
  },
  {
    id: "cf-oreveins",
    name: "Rich Veins",
    author: "Quarrylight",
    version: "2.0.0",
    kind: "palschema",
    source: "curseforge",
    sourceId: "1074401",
    url: "https://www.curseforge.com/",
    downloads: 210400,
    endorsements: 5100,
    category: "World",
    description: "Increases ore and Soralite node HP and drop tables. Must live on the dedicated server.",
    gameVersions: [...V10],
    requires: ["ue4ss", "palschema"],
    serverCompatible: true,
    clientCompatible: true,
    sizeKb: 22,
    updatedAt: "2026-09-10T00:00:00.000Z",
    tags: ["gathering", "server", "1.0"],
  },
];

export function catalogBySource(source: CatalogMod["source"]) {
  return CATALOG.filter((m) => m.source === source);
}

export function searchCatalog(query: string, source?: CatalogMod["source"]) {
  const q = query.trim();
  return CATALOG.filter((m) => {
    if (source && m.source !== source) {
      const parsed = parseModQuery(q);
      if (!(parsed.source && parsed.source === m.source && parsed.sourceId)) return false;
    }
    return matchesModQuery(m, q, source);
  });
}

export function catalogToHit(mod: CatalogMod): SearchHit {
  return {
    id: mod.id,
    name: mod.name,
    author: mod.author,
    version: mod.version,
    source: mod.source,
    sourceId: mod.sourceId,
    url: mod.url,
    downloads: mod.downloads,
    description: mod.description,
    kind: mod.kind,
    updatedAt: mod.updatedAt,
    serverCompatible: mod.serverCompatible,
    gameVersions: mod.gameVersions,
    requires: mod.requires,
    files: filesForHit({
      name: mod.name,
      kind: mod.kind === "framework" ? "palschema" : mod.kind,
      files: undefined,
      sizeKb: mod.sizeKb,
      source: mod.source,
    }),
  };
}
