<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Palnest.Core\Palnest.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>2.0.0</Version>
    <AssemblyName>Palnest</AssemblyName>
    <Product>Palnest</Product>
    <Description>Palworld Server and Mod Manager</Description>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
