/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCheckerRouteImport } from './routes/_app/checker'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppFrameworksRouteImport } from './routes/_app/frameworks'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppModsRouteImport } from './routes/_app/mods'
import { Route as AppMonitorRouteImport } from './routes/_app/monitor'
import { Route as AppOptimizeRouteImport } from './routes/_app/optimize'
import { Route as AppServerRouteImport } from './routes/_app/server'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTunnelsRouteImport } from './routes/_app/tunnels'
import { Route as AppWorldsRouteImport } from './routes/_app/worlds'
import { Route as AppDiscoverModIdRouteImport } from './routes/_app/discover.$modId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckerRoute = AppCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppFrameworksRoute = AppFrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppModsRoute = AppModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizeRoute = AppOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => AppRoute,
} as any)
const AppServerRoute = AppServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTunnelsRoute = AppTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsRoute = AppWorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverModIdRoute = AppDiscoverModIdRouteImport.update({
  id: '/$modId',
  path: '/$modId',
  getParentRoute: () => AppDiscoverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/status': typeof StatusRoute
  '/checker': typeof AppCheckerRoute
  '/discover': typeof AppDiscoverRouteWithChildren
  '/frameworks': typeof AppFrameworksRoute
  '/logs': typeof AppLogsRoute
  '/mods': typeof AppModsRoute
  '/monitor': typeof AppMonitorRoute
  '/optimize': typeof AppOptimizeRoute
  '/server': typeof AppServerRoute
  '/settings': typeof AppSettingsRoute
  '/tunnels': typeof AppTunnelsRoute
  '/worlds': typeof AppWorldsRoute
  '/discover/$modId': typeof AppDiscoverModIdRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/status': typeof StatusRoute
  '/checker': typeof AppCheckerRoute
  '/discover': typeof AppDiscoverRouteWithChildren
  '/frameworks': typeof AppFrameworksRoute
  '/logs': typeof AppLogsRoute
  '/mods': typeof AppModsRoute
  '/monitor': typeof AppMonitorRoute
  '/optimize': typeof AppOptimizeRoute
  '/server': typeof AppServerRoute
  '/settings': typeof AppSettingsRoute
  '/tunnels': typeof AppTunnelsRoute
  '/worlds': typeof AppWorldsRoute
  '/': typeof AppIndexRoute
  '/discover/$modId': typeof AppDiscoverModIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/status': typeof StatusRoute
  '/_app/checker': typeof AppCheckerRoute
  '/_app/discover': typeof AppDiscoverRouteWithChildren
  '/_app/frameworks': typeof AppFrameworksRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/mods': typeof AppModsRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/optimize': typeof AppOptimizeRoute
  '/_app/server': typeof AppServerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tunnels': typeof AppTunnelsRoute
  '/_app/worlds': typeof AppWorldsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/discover/$modId': typeof AppDiscoverModIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/status'
    | '/checker'
    | '/discover'
    | '/frameworks'
    | '/logs'
    | '/mods'
    | '/monitor'
    | '/optimize'
    | '/server'
    | '/settings'
    | '/tunnels'
    | '/worlds'
    | '/discover/$modId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/status'
    | '/checker'
    | '/discover'
    | '/frameworks'
    | '/logs'
    | '/mods'
    | '/monitor'
    | '/optimize'
    | '/server'
    | '/settings'
    | '/tunnels'
    | '/worlds'
    | '/'
    | '/discover/$modId'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/status'
    | '/_app/checker'
    | '/_app/discover'
    | '/_app/frameworks'
    | '/_app/logs'
    | '/_app/mods'
    | '/_app/monitor'
    | '/_app/optimize'
    | '/_app/server'
    | '/_app/settings'
    | '/_app/tunnels'
    | '/_app/worlds'
    | '/_app/'
    | '/_app/discover/$modId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checker': {
      id: '/_app/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof AppCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frameworks': {
      id: '/_app/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof AppFrameworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mods': {
      id: '/_app/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof AppModsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/optimize': {
      id: '/_app/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof AppOptimizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/server': {
      id: '/_app/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AppServerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tunnels': {
      id: '/_app/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof AppTunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/worlds': {
      id: '/_app/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof AppWorldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover/$modId': {
      id: '/_app/discover/$modId'
      path: '/$modId'
      fullPath: '/discover/$modId'
      preLoaderRoute: typeof AppDiscoverModIdRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
  }
}

interface AppDiscoverRouteChildren {
  AppDiscoverModIdRoute: typeof AppDiscoverModIdRoute
}

const AppDiscoverRouteChildren: AppDiscoverRouteChildren = {
  AppDiscoverModIdRoute: AppDiscoverModIdRoute,
}

const AppDiscoverRouteWithChildren = AppDiscoverRoute._addFileChildren(
  AppDiscoverRouteChildren,
)

interface AppRouteChildren {
  AppCheckerRoute: typeof AppCheckerRoute
  AppDiscoverRoute: typeof AppDiscoverRouteWithChildren
  AppFrameworksRoute: typeof AppFrameworksRoute
  AppLogsRoute: typeof AppLogsRoute
  AppModsRoute: typeof AppModsRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppOptimizeRoute: typeof AppOptimizeRoute
  AppServerRoute: typeof AppServerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTunnelsRoute: typeof AppTunnelsRoute
  AppWorldsRoute: typeof AppWorldsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckerRoute: AppCheckerRoute,
  AppDiscoverRoute: AppDiscoverRouteWithChildren,
  AppFrameworksRoute: AppFrameworksRoute,
  AppLogsRoute: AppLogsRoute,
  AppModsRoute: AppModsRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppOptimizeRoute: AppOptimizeRoute,
  AppServerRoute: AppServerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTunnelsRoute: AppTunnelsRoute,
  AppWorldsRoute: AppWorldsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
